### ISSUE TITLE
Intended inputs and use cases (string vs domain)

### ISSUE THREAD

**Issue by saurori** [Zenithar/go-typogenerator#2]
I am in the process of writing a README and was comparing strategies to [dnstwist](https://github.com/elceef/dnstwist) which I assume is the primary inspiration for this library.

One main difference is that dnstwist takes an input of a full domain whereas this library expects a domain string without a TLD (which I assume given the intention/description in the current README). Given the current set of strategies, this does not pose any problems. However, this does create potential limitations for additional strategies based around TLDs as the library does not expect to know the TLD. For example, a strategy of "wrong tld" would not be possible (`example.com` -> `example.io` etc).

What are your thoughts on adding in domain parsing? The library could either expect a domain (and return error if not) or parse domains and leave strings as is but some strategies may only operate on parsed domains.

**Comment by Zenithar** [comment]
In fact typosquatting is not only used for Domain, that's why I have splitted in 2 commands (typogen, and tldexpand).
Yes main idea come from dnstwist which I mention in my companion article (https://blog.zenithar.org/post/2017/01/21/domain-typosquatting/ [FR]). You can invoke like this :

$> typogen -s "zenithar" | tldexpand | resolve >> typo_squatter.csv

This can comply the unix command philosophy. I have also used typography on email address and username, that's why typogen does the permutations on the given string only.

**Comment by saurori** [comment]
What if I create another function specific to Domain fuzzing, that splits and tracks TLD. Something like:

```
func FuzzDomain(domain string, strategies ...strategy.Strategy) ([]FuzzResult, error) {
    ...
    parsed, err := publicsuffix.Parse(domain)
    ...
    r := FuzzResult{
        StrategyName: s.GetName(),
        Domain:       parsed.TRD + parsed.SLD,
        Tld:          parsed.TLD,
    }
   ...
```

**Comment by Zenithar** [comment]
Hmm I think you could invoke typogen with a splitted domain, then add TLD after permutations. It would leave the library clean from DNS domain concept.

**Comment by saurori** [comment]
Yes you could but that does not support additional strategies involving TLD. Here are 2 possible strategies, one of which dnstwist implements:

1. TLD swapping. Download a list of TLDs from the public suffix list and swap. So `example.com` -> `example.co`
2. TLD repeat. `example.com` -> `examplecom.com`

**Comment by Zenithar** [comment]
Ok I didn't think about these usecases ^^
